apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-api-config
  namespace: simple-api
  labels:
    app.kubernetes.io/name: simple-api
    app.kubernetes.io/managed-by: argocd
data:
  APP_NAME: "simple-api"
  ENVIRONMENT: "production"
  DOMAIN: "api.ticarethanem.net"
  LOG_LEVEL: "info"
  TZ: "UTC"
